#02. 2차원 배열

2차원 배열의 생성

In [2]:
import numpy as np

In [19]:
# 철수의 학년-과목별 점수

grade = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
])

In [4]:
grade.ndim

2

원소의 데이터 타입

In [5]:
grade.dtype

dtype('int32')

### 2차원 배열의 기초 통계량

### (1) 각 열끼리 더함 (세로로 덧셈)

결과 타입은 numpy의 1차 배열

In [7]:
s1 = np.sum(grade, axis=0)  
print(type(s1))
s1

<class 'numpy.ndarray'>


array([278, 250, 242, 206])

### (2) 각 행끼리 더함 (가로로 덧셈)

In [8]:
s2 = np.sum(grade, axis=1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([314, 330, 332])

### [4] 조건검색
#### (1) boolean 타입으로 인덱싱

In [9]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

### (2) 비교식에 의한 검색
80점 이상인지 판별하여 조건에 맞는 데이터만 추려냄

In [16]:
result2 = grade[grade >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

### (3) AND 검색

In [17]:
result3 = grade[np.logical_and(grade>=80, grade<=90)]
result3

array([80, 88, 90, 80, 88, 82])

### (4) OR 검색

In [18]:
result4 = grade[np.logical_or(grade<80, grade>90)]
result4

array([98, 72, 64, 72, 92, 70])

## #03. 정형화된 배열 생성

### [1] 모든 원소가 '0'인 배열

In [11]:
a = np.zeros([3, 4])    # 리스트나 튜플로 두 번 감싸 2차원임을 말해줘야함.
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### [2] 모든 원소가 '2'인 배열

In [13]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### [3] 모든 원소가 특정값인 배열

In [14]:
np.full([3,4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### [4] 단위행렬

대각선으로 '1'이고 나머지 원소는 모두 '0'인 배열

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 0부터 1까지

4행 3열인 2차원 배열

In [20]:
np.random.rand(4,3)

array([[0.22949867, 0.79984938, 0.28022673],
       [0.89761487, 0.10744467, 0.37782014],
       [0.94923482, 0.62628291, 0.61183901],
       [0.15706972, 0.92472612, 0.3670534 ]])

### [2] 주어진 범위 안에서 정수값을 갖는 랜덤 배열

#### 0부터 9사이의 랜덤값 10개의 원소를 갖는 1차원 배열

In [21]:
np.random.randint(0,9,10)

array([7, 2, 8, 7, 5, 4, 6, 7, 5, 4])

#### 0부터 9사이의 랜덤값을 갖는 3행 4열의 2차 배열

In [22]:
np.random.randint(0,9,(3,4))

array([[2, 2, 7, 8],
       [3, 2, 5, 8],
       [4, 0, 4, 0]])

### [3] 표준 정규 분포를 따르는 랜덤 배열

#### 1차원 배열

In [23]:
np.random.randn(10)

array([ 1.21781764,  0.71155653, -1.3693391 , -0.80942755,  0.43215672,
        1.4410116 ,  0.6756953 , -0.82551528, -0.45933844,  0.41170505])

#### 2차원 배열

In [24]:
np.random.randn(4, 3)

array([[-0.85764716,  0.0215656 ,  0.94156154],
       [ 0.09266179,  0.3788998 , -0.27408569],
       [ 0.40068207, -0.14654044,  0.37841838],
       [ 0.8689491 , -0.25437014,  0.58498443]])

### [4] 정규분포를 직접 설정

#### 1차원 배열

평균은 '0', 표준편차 '1'의 정규 분포에서 10개의 수를 추출

In [25]:
np.random.normal(0, 1, 10)

array([-0.01750189, -0.69379964,  0.5737231 , -0.83831786, -0.10570577,
       -0.12426361,  0.34547835, -0.23362465, -2.41234758, -0.54479155])

#### 2차원 배열

In [26]:
np.random.normal(0,1,(4,3))

array([[-0.31234522,  0.65831692,  0.89585062],
       [-0.35962565, -0.04306933, -1.06091129],
       [-0.58867707, -0.29556649, -0.27898196],
       [ 1.35524812, -0.52550356,  0.33303884]])

### [5] 랜덤값 고정

랜덤이란 사전에 잘 섞여 있는 숫자 셋을 순차적으로 꺼내는 것을 의미

랜덤시드는 몇 번째 숫자셋인지를 의미하는 값

이 값을 고정하면 특정 숫자셋만 사용하라는 의미

In [28]:
np.random.seed(777)
np.random.normal(0, 1, (4, 3))      # 여러번 실행해도 같은 숫자 세트가 나옴

array([[-0.46820879, -0.82282485, -0.0653801 ],
       [-0.71336192,  0.90635089,  0.76623673],
       [ 0.82605407, -1.32368279, -1.75244452],
       [ 1.00244907,  0.54480945,  1.8951609 ]])