# Numpy 형태변환
## #01. 준비과정
### [1] 패키지 참조

In [1]:
import numpy as np

## #02. 타입변환

배열 원소의 데이터 타입을 변환하는 방법에는 'astype()'메서드를 사용하는 방법과 'asarray()'함수를 사용하는 방법이 있다.

### [1]'astype()'메서드 사용하기
#### (1) 실습을 위한 원본 배열 구성

In [2]:
arr1 = np.arange(10)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int32


#### (2) 실수('float')타입으로 변환

In [3]:
arr2 = arr1.astype('float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


#### (3) 문자열('str')타입으로 변환

In [4]:
arr3 = arr1.astype('str')
print("형변환 후의 배열:",  arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U11


### [2] 'asarray()'함수 사용하기

#### (1) 원본 배열 구성

In [5]:
arr1 = np.arange(10, 20)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int32


#### (2) 실수('float')타입으로 변환

변환할 원본 배열과 변환될 타입(dtype)을 파라미터로 설정한다.

In [6]:
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


#### (3) 문자열('str')타입으로 변환

In [7]:
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후의 배열:",arr3)
print("변환된 후의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 후의 데이터 타입: <U11


## #03. 차원 변환
### [1] 1차원 배열을 다차원으로 변환하기
#### (1) 1~20까지의 원소를 갖는 1차원 배열

In [15]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### (2) (4,5) 2차원 배열로 변환

'reshape(행, 열)' 메서드를 사용한다.



In [16]:
x = origin.reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### (3) 변환할 수 없는 경우
'행, 열'로 재구성했을 경우 원소의 수가 남거나 모자라서는 안된다.
아래의 경우는 원소의 수가 3행, 7열로 구성될 수 없기 때문에 에러가 발생

In [17]:
origin.reshape(3, 7)

ValueError: cannot reshape array of size 20 into shape (3,7)

#### (4) 3차원 배열로 변환

In [18]:
y = origin.reshape(2, 2, 5) # 2행 5열이 2개.
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### [2] 차원 축소

#### (1) 원본 배열

In [19]:
origin = np.array([[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9],
                   [10, 11, 12, 13, 14],
                   [15, 16, 17, 18, 19]])
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### (2) 1차원으로 축소

In [20]:
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

1차원으로 변환할 경우 일일이 원소의 수를 세기는 번거로우므로 'shape'를 구해서 활용


In [21]:
rows, cols = origin.shape # 튜플임
rows, cols

(4, 5)

In [22]:
z = origin.reshape(rows*cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### [3] '-1'의 의미

reshape를 활용하는 경우를 보다 보면 입력 파라미터로 '-1'이 들어간 경우가 종종 있다.

'reshape()'의 '-1'이 의미하는 바는, 변경된 배열의 '-1'위치의 차원은 "원래 배열의 길이와 남은 차원으로부터 추정"이 된다는 뜻이다.

> 'n'개라는 의미로 이해하자.

#### (1) 'reshape(-1, 정수)' : 행의 위치에 -1인 경우

In [10]:
origin = np.array([[0, 1, 2, 3],
                   [4, 5, 6, 7],
                   [8, 9, 10, 11]])
x = origin.reshape(-1, 1) # 행은 알아서 맞추고, 열은 1개.
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

##### 행의 수에 관계 없이 3열을 갖는 2차원 배열

In [11]:
z = origin.reshape(-1,3)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### (2) 'reshape(정수, -1)' : 열의 위치에 '-1'인 경우

##### 원본 배열

In [25]:
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### 열의 수에 관계 없이 2행을 갖는 2차원 배열로 재구성

In [26]:
x = origin.reshape(2, -1)
x


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

##### 열의 수에 관계 없이 3행을 갖는 2차원 배열로 재구성

In [27]:
y = origin.reshape(3, -1)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### 열의 수에 관계 없이 4행을 갖는 2차원 배열로 재구성

In [28]:
z = origin.reshape(4, -1)
z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### (3) 'reshape(-1)'인 경우

##### 원본 배열

In [14]:
origin = np.array([[0, 1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10, 11] ])
origin

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

##### 1차원 배열로 변환

행의 수는 지정되지 않고, 열의 수에 -1을 지정

In [29]:
x = origin.reshape(-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### 2차원 배열로 변환

행의 수는 1개이고 열의 수는 -1을 지정

In [31]:
y = origin.reshape(1,-1)    # 파라미터 2개 -> 2차원배열
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])